remote_theme: niklasbuschmann/contrast@v2.11
plugins:
- jekyll-remote-theme

title: "jsMind"
author: "hizzgdev@163.com"

show_sidebar: true

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", title: "jsMind", icon: "bolt", sidebaricon: "bolt"}
  - {url: "/docs/", title: "Document", icon: "book", sidebaricon: "book"}
  - {url: "https://github.com/hizzgdev/jsmind", title: "GitHub", icon: "github", sidebaricon: "githuub"}
