remote_theme: niklasbuschmann/contrast@v2.11
plugins:
- jekyll-remote-theme

title: "jsMind"
author: "hizzgdev@163.com"
description: "&copy; 2022 - 2023"

show_sidebar: true

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://github.com/hizzgdev/jsmind", title: "GitHub"}
  - {url: "/docs/", title: "Document"}
  - {url: "/jsmind/", title: "About"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hizzgdev@163.com"}
  - {title: Github, icon: github, url: "https://github.com/hizzgdev/jsmind"}