remote_theme: https://github.com/hizzgdev/contrast
plugins:
- jekyll-remote-theme

title: "jsMind"
author: "hizzgdev@163.com"
description: " "

show_sidebar: true

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", title: "About jsMind", icon: "bolt"}
  - {url: "/docs/", title: "Documents", icon: "book"}
  - {url: "https://github.com/hizzgdev/jsmind", title: "GitHub", icon: "github"}
