remote_theme: niklasbuschmann/contrast@v2.11
plugins:
- jekyll-remote-theme

title: "jsMind"
author: "hizzgdev@163.com"
description: " "

show_sidebar: true

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", title: "jsMind"}
  - {url: "/docs/", title: "Document"}
  - {url: "https://github.com/hizzgdev/jsmind", title: "GitHub"}
